### ISSUE TITLE
Bumping part required by another ignores the requiring part

### ISSUE THREAD

**Issue by mark-bromell** [mark-bromell/myver#4]
## Example config

```yaml
parts:
  major:
    value: 3
    requires: minor

  minor:
    value: 9
    prefix: '.'
    requires: patch

  patch:
    value: 2
    prefix: '.'

  pre:
    value: null
    prefix: '-'
    requires: prenum
    identifier:
      strings: [ 'alpha', 'beta', 'rc' ]

  prenum:
    prefix: '.'
    value: null
    number:
      start: 1
```

## Problem

The above config will give a version of `3.9.2`, and if we do `myver --bump prenum` then we will get a version of `3.9.2.1`.

The `pre` part will remain as `null` if you only bump `prenum`. We should instead expect to get a version of `3.9.2-alpha.1` because the `pre` part requires the `prenum` part, and they should always exist together.
